# -*- coding: utf-8 -*-

FOREGROUND_DARK_BLACK = 0x0000
FOREGROUND_DARK_RED = 0x0004  # text color contains red.
FOREGROUND_DARK_GREEN = 0x0002  # text color contains green.
FOREGROUND_DARK_BLUE = 0x0001  # text color contains blue.
FOREGROUND_DARK_YELLOW = FOREGROUND_DARK_RED | FOREGROUND_DARK_GREEN
FOREGROUND_DARK_MAGENTA = FOREGROUND_DARK_RED | FOREGROUND_DARK_BLUE
FOREGROUND_DARK_CYAN = FOREGROUND_DARK_GREEN | FOREGROUND_DARK_BLUE
FOREGROUND_DARK_WHITE = (
    FOREGROUND_DARK_RED |
    FOREGROUND_DARK_GREEN |
    FOREGROUND_DARK_BLUE
)

# 0x0008 text color is intensified.

FOREGROUND_BRIGHT_BLACK = FOREGROUND_DARK_BLACK | 0x0008
FOREGROUND_BRIGHT_RED = FOREGROUND_DARK_RED | 0x0008
FOREGROUND_BRIGHT_GREEN = FOREGROUND_DARK_GREEN | 0x0008
FOREGROUND_BRIGHT_BLUE = FOREGROUND_DARK_BLUE | 0x0008
FOREGROUND_BRIGHT_YELLOW = FOREGROUND_DARK_YELLOW | 0x0008
FOREGROUND_BRIGHT_MAGENTA = FOREGROUND_DARK_MAGENTA | 0x0008
FOREGROUND_BRIGHT_CYAN = FOREGROUND_DARK_CYAN | 0x0008
FOREGROUND_BRIGHT_WHITE = FOREGROUND_DARK_WHITE | 0x0008

BACKGROUND_DARK_BLACK = 0x0000
BACKGROUND_DARK_RED = 0x0040  # background color contains red.
BACKGROUND_DARK_GREEN = 0x0020  # background color contains green.
BACKGROUND_DARK_BLUE = 0x0010  # background color contains blue.
BACKGROUND_DARK_YELLOW = BACKGROUND_DARK_RED | BACKGROUND_DARK_GREEN
BACKGROUND_DARK_MAGENTA = BACKGROUND_DARK_RED | BACKGROUND_DARK_BLUE
BACKGROUND_DARK_CYAN = BACKGROUND_DARK_GREEN | BACKGROUND_DARK_BLUE
BACKGROUND_DARK_WHITE = (
    BACKGROUND_DARK_RED |
    BACKGROUND_DARK_GREEN |
    BACKGROUND_DARK_BLUE
)

# 0x0080 background color is intensified.

BACKGROUND_BRIGHT_BLACK = BACKGROUND_DARK_BLACK | 0x0080
BACKGROUND_BRIGHT_RED = BACKGROUND_DARK_RED | 0x0080
BACKGROUND_BRIGHT_GREEN = BACKGROUND_DARK_GREEN | 0x0080
BACKGROUND_BRIGHT_BLUE = BACKGROUND_DARK_BLUE | 0x0080
BACKGROUND_BRIGHT_YELLOW = BACKGROUND_DARK_YELLOW | 0x0080
BACKGROUND_BRIGHT_MAGENTA = BACKGROUND_DARK_MAGENTA | 0x0080
BACKGROUND_BRIGHT_CYAN = BACKGROUND_DARK_CYAN | 0x0080
BACKGROUND_BRIGHT_WHITE = BACKGROUND_DARK_WHITE | 0x0080

UNDERSCORE = 0x8000
BOLD = 0x2000

BACKGROUND_DARK_BLACK = 0x0200


